### ISSUE TITLE
Hinky Note Link Behavior

### ISSUE THREAD

**Issue by eleanorkonik** [valentine195/obsidian-fantasy-calendar#11]
No relevant errors in console. 

![2021-11-09-fantasy-map-note-broke](https://user-images.githubusercontent.com/75856959/140972926-b3e197f8-3471-453c-a895-9e7d5450350c.gif)

I haven't changed my note naming schema, and you haven't changed anything obviously relevant, so this one is a bit of a mystery.

**Comment by valentine195** [comment]
Heya, this should be fixed in 1.5.3.
