### ISSUE TITLE
Leap Year Offset not working

### ISSUE THREAD

**Issue by cenycal** [valentine195/obsidian-fantasy-calendar#13]
Bless you for creating this plugin. Truthfully it was the deciding factor in switching my ttrpg notes to Obsidian.

**Issue:** Setting an Offset for the Leap Year is not shifting the occurrence of the extra day.

**My Actions:** I have tried deleting the leap day and recreating it to see if it was a bug that occurred when I imported the calendar. Deleting the old leap day successfully removed all occurrences but the new leap day still can not be offset.

**Comment by valentine195** [comment]
Sorry this took so long, should be fixed now!
