### ISSUE TITLE
Gregorian Events Not Updating

### ISSUE THREAD

**Issue by eleanorkonik** [valentine195/obsidian-fantasy-calendar#14]
We discussed this on Discord but here's a gif to jog your memory, idk how to describe it but the events are all hinky. 
![idk how to desc this](https://user-images.githubusercontent.com/75856959/143374709-fe57f31b-34cc-4aeb-9160-8d5a1a36c0ab.gif)

**Comment by valentine195** [comment]
This should be fixed in the latest release.
