### ISSUE TITLE
Events displaying on incorrect days.

### ISSUE THREAD

**Issue by ngzaharias** [valentine195/obsidian-fantasy-calendar#15]
I've noticed that when you switch between months in the calendar, all events of the month you just came from remain displayed in the new month. 

Repo:
- create "Faerun" preset
- go to Midwinter using the > arrow
- go to Alturiak using the > arrow
- create an event in Alturiak
- go to Ches using the > arrow

Both the midwinter event and the custom event will be present in the Ches month.

**Comment by ngzaharias** [comment]
Further more, deleting a custom event doesn't remove it immediately from the page. It looks like the page needs to refresh its events after commands.

**Comment by valentine195** [comment]
This should be fixed in the latest release.
