### ISSUE TITLE
Create custom event incorrectly showing

### ISSUE THREAD

**Issue by ngzaharias** [valentine195/obsidian-fantasy-calendar#16]
Repo:
- create calendar using "Faerun" present
- go to Midwinter day
- click on the midwinter event to display the event text
- click below the midwinter event to display the "create custom event" dialog
- close the custom event dialog
- click the midwinter event again

The custom event dialog will display at the same time as the midwinter event text will be.

**Comment by valentine195** [comment]
This should be fixed in the latest release.
