### ISSUE TITLE
Default config directory

### ISSUE THREAD

**Issue by Rubiginosa** [valentine195/obsidian-fantasy-calendar#18]
I just learned about this plugin (No topic on the forums!) - you've essentially consolidated my entire D&D workflow by now, which is fantastic.

It would be great if you could implement the same feature that Obsidian Leaflet has to change the default plugin directory, so we can have cross-device syncing. Thanks loads!

**Comment by valentine195** [comment]
Forgot to do this yesterday, sorry :) should be working in 1.9.0
