### ISSUE TITLE
Add information of current day of the year

### ISSUE THREAD

**Issue by lanice** [valentine195/obsidian-fantasy-calendar#19]
It would be fantastic to have the option to show which day in the current year it is for a date. So for example, in the Harptos Calendar (Forgotten Realms), the 10th of Nightal (which is the twelfth month of a year) would be the day 345.

I guess having an option to turn this on/off would make sense to not be too intrusive to people who are not interested in that, similar to toggling showing week numbers and moons maybe. Example:
![fantasy-calendar-mock-0](https://user-images.githubusercontent.com/1871704/144757876-6318ff9d-60dd-435b-b31c-8e952908ec8f.png)
In the mock-up I called it "Show Day Numbering", but maybe "Show Day of the Year", "Show Day number", or something like this would be better.

As for the placement of the information itself, I don't know if it makes sense to put it next to each number of the monthly view, since that might get too crowded. For me personally, just adding it to the detail view of a day underneath the calendar would be enough, like this:
![fantasy-calendar-mock-1](https://user-images.githubusercontent.com/1871704/144757999-18557008-bdbc-438f-889e-61fc9aeb6fbf.png)

Thank you for this awesome tool, and of course also the others you made!

**Comment by lanice** [comment]
Looking at the screenshot again, I just realized it also would not hurt to include the range of days of the current month above the month headline, like this:
![fantasy-calendar-mock-2](https://user-images.githubusercontent.com/1871704/144759351-fe094542-1d65-4e68-a529-394f97c76e1a.png)

Just throwing ideas out there :)

**Comment by valentine195** [comment]
Added in 1.10.0

**Comment by valentine195** [comment]
That's a good idea. I actually had added the day number under the month, but removed it because it was contextless if you weren't on the current month. I like this more!

My kid just woke up, so I'll try to get it in tonight / tomorrow :)
