### ISSUE TITLE
Moon Phases Drifting

### ISSUE THREAD

**Issue by Cubius** [valentine195/obsidian-fantasy-calendar#20]
Working with the Forgotten Realms Calendar of Harptos I noticed that the moon phases are entirely inaccutate.
Perhaps the decimal for Cycle duration is not handled properly, or perhaps this is related to issues with intercalendary leap days #12 and #13.
(Comparison using the [Calendar Tool ](http://archive.wizards.com/default.asp?x=dnd/frx/20050525x)from WotC's archived old site.)
![grafik](https://user-images.githubusercontent.com/15717384/144825777-2c3779e1-b130-4012-9009-0f5701900651.png)
![grafik](https://user-images.githubusercontent.com/15717384/144825882-31bb9d0d-0d42-4edd-8d94-a4be420a2fe1.png)

**Comment by valentine195** [comment]
Thanks for letting me know, this is fixed in 1.10.1
