### ISSUE TITLE
Selecting a heading in the edit / create event popup does nothing

### ISSUE THREAD

**Issue by simonfruehauf** [valentine195/obsidian-fantasy-calendar#21]
![fc-bug](https://user-images.githubusercontent.com/25452923/145706830-95fac437-e952-4df2-816c-6c17f192558d.gif)

As seen in the gif above, when selecting a heading (with #) in the event popup, it defaults back to only the note. This also clears any name given to the event.

**Comment by valentine195** [comment]
Thanks, I’ll take a look.

**Comment by CrazyCookieBuddy** [comment]
If the information is there, then there's another issue, since even if I manually put it in (e.g. Note#Header) and then save, it doesn't link to the header but only the note.
