### ISSUE TITLE
Fantasy Calendar is very slow when using file-name parsing

### ISSUE THREAD

**Issue by HEmile** [valentine195/obsidian-fantasy-calendar#27]
Hi, thank you so much for adding the file-name parsing for compatibility with daily notes! However, in my experience it makes the plugin _very_ slow. For instance, moving between months takes about 5 seconds to load, while in the Calendar plugin it is instant. Is it maybe needed to index this?

As a bit of background, I have about 600 daily notes, I think.

**Comment by valentine195** [comment]
Okay, I’ve been wanting to do this anyway because the current logic for getting events on a given date is extremely inefficient. Guess this is a good excuse 😁

**Comment by valentine195** [comment]
The latest release is now optimized for large amounts of events.
