### ISSUE TITLE
Feature Request: Jump to Date via Command Palette

### ISSUE THREAD

**Issue by eleanorkonik** [valentine195/obsidian-fantasy-calendar#28]
I have a bunch of daily notes from months and months ago and it would be awesome if I could open them and then run a command to "view calendar entry associated with this day" or whatever the equivalent of "open day" is but for the note I'm in if it's a dated note. 

🙈 this isn't important,  just a fun little add-on that would make rummaging around in my old daily notes a little easier.

**Comment by valentine195** [comment]
Added in 1.12.0 :)

**Comment by valentine195** [comment]
Specifically the command is "View Note Event"
