### ISSUE TITLE
Event Title

### ISSUE THREAD

**Issue by Catnap63** [valentine195/obsidian-fantasy-calendar#29]
If the event title is too long on the Fantasy calendar website I see a "+1" in Obsidian for the event.  But there does not appear to be any way of view the event.  Am I missing something?  Thanks.

**Comment by valentine195** [comment]
If you open the day view for that day (by right-clicking > Open Day, or double click the day if it has events), it will show all the events.

Please note that this only works if the calendar is in the side pane.

I will add a better way to view all events, though. Possibly right-click > View Events.
