### ISSUE TITLE
FR: Add events created by the UI to the notes frontmatter

### ISSUE THREAD

**Issue by HEmile** [valentine195/obsidian-fantasy-calendar#32]
Creating an event using the "New event" button in the calendar currently stores the resulting event in a fantasy-calendar specific json file. However, I prefer to have my vault self contained, that is, all data should be part of either the notes or the attachments. Therefore, I'd prefer if these events instead are added to the frontmatter of the linked note!

**Comment by valentine195** [comment]
This is now possible via a toggle in settings.
