### ISSUE TITLE
Bug - Imported JSON File calender from fantasy-calendar.com not working

### ISSUE THREAD

**Issue by PyPS-PowerUser** [valentine195/obsidian-fantasy-calendar#35]
Hi I tested this with Obsidian v0.13.19 and Fantasy Calender v 1.12.1. No other Community Plug Ins installed.

When I import my Calender from fantasy-calendar.com as a JSON File [calendar_Mortaru.txt](https://github.com/valentine195/obsidian-fantasy-calendar/files/7849767/calendar_Mortaru.txt) (renamed to txt for GitHub) into it, the sentence that no calender exist goes away but no calender is shown. Using a preset works flawlessly.

When I recreate the calender in the plug in it works.

**Comment by valentine195** [comment]
Hi! Sorry this took so long - I was working on a big behind-the-scenes update for this plugin. Now that its done, I'm working through these outstanding issues.

It seems I fixed this as part of the update I was talking about. This calendar imports for me fine, and shows up in the list.

**Comment by PyPS-PowerUser** [comment]
Tested it and can confirm that it works now. Thanks!
