### ISSUE TITLE
Feature Request - Fast year selection/change

### ISSUE THREAD

**Issue by PyPS-PowerUser** [valentine195/obsidian-fantasy-calendar#37]
I want to create a big calender for my game which thousands of years but there is no fast way to select a specific year.

As a workaround I use the "Current Date" in the calender creation settings but an entry field for a number could resolve that issue.

**Comment by valentine195** [comment]
If you click the settings cog near the calendar, there is a “View Date” option - does that do what you want?

**Comment by PyPS-PowerUser** [comment]
Not really since it only has a selection for day and month but not for year.

**Comment by valentine195** [comment]
This isn't there for you?
![image](https://user-images.githubusercontent.com/38669521/149834259-6f4e1dd4-2287-4d2e-855e-9262c0db711c.png)

**Comment by PyPS-PowerUser** [comment]
I found out that it was bugged in my vault. When I tried to recreate the issue in a testvault it worked perfectly. Funny enough my entire calender was bugged and couldn't be edited anymore so I had to recreate it. Good thing is there was not much to it so far.

![image](https://user-images.githubusercontent.com/42782398/150010035-81c232f5-2799-406f-8261-a74c98947bd7.png)
