### ISSUE TITLE
[Feature Request]: Allow event to happen every x {days, months, years} from y

### ISSUE THREAD

**Issue by namtrah** [valentine195/obsidian-fantasy-calendar#38]
In your documentation, it would seem that one can only add reoccurring events happening on a specific day of the month, month  of the year, etc. 

I would like to have an event that happens every x number of days (say 10 days starting on the 2nd of a particular month). 

Is that possible today? And if not, could you add it?

**Comment by valentine195** [comment]
This isn’t possible no. Let me think about it - it will require a change to the way events are hashed and indexed.

**Comment by valentine195** [comment]
Hi, this was added in the latest release.

You can add intervals in the Edit/Create Event modal.
