### ISSUE TITLE
Interaction with Tasks Plugin

### ISSUE THREAD

**Issue by namtrah** [valentine195/obsidian-fantasy-calendar#41]
More of a FR. IF it could be possible to interact/react with the [Tasks Plugin](https://github.com/schemar/obsidian-tasks) allowing tasks to be checked off in the Active Calendar in Fantasy Calendar. Adding FR to theirs as well.

**Comment by valentine195** [comment]
What would this look like on the calendar? It doesn't really have the concept of tasks, just events that are tied to a single note.

**Comment by namtrah** [comment]
True, i think this should go in the other direction. A FR by Tasks Plugin to work with your API.
