### ISSUE TITLE
Update filename when filename changes

### ISSUE THREAD

**Issue by eleanorkonik** [valentine195/obsidian-fantasy-calendar#6]
I often add a file to the event, then change the filename later once I have a less placeholdery title for the story / location / whatever. But fantasy calendar doesn't detect these changes, so winds up out of date, so when I use it to open the note, it makes a new note with the old name.

**Comment by valentine195** [comment]
This works for me. Are there any errors in the console when you rename a file? If not, does this behavior happen in a new vault?

**Comment by eleanorkonik** [comment]
No errors in the console. I'm on the latest version of fantasy calendar. Confirmed the behavior is the same in a test vault with a fresh install of fantasy calendar. I can make a gif if it would help?

**Comment by valentine195** [comment]
Yes please
